### PR TITLE
Fix missing aspects during intialisation

### LINKED ISSUE #10529: terminus doesn't show up in the thaumcraft research table
### Your GTNH Discord Username

Tralomine#5809

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

all aspects should show up in the research table to be used in research

### The Reality

there are 67 aspects in the pack and the research table layout can only fit 66, so when every aspect is known, terminus is cut off the list and can't be used in researches to make links

image

### Your Proposal

just let  one more line of aspects be displayed, as the UI is already the right size for that

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by TheElan**
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10529
Needed a buildscript upgrade to building

### CODE REVIEW

File: src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/ThaumcraftResearchTweaks.kt [hunk 1]
```diff
@@ -35,7 +35,7 @@ object ThaumcraftResearchTweaks {
   lateinit var singletonInitializer: SingletonInitializer
 
   @Mod.EventHandler
-  fun onInit(event: FMLInitializationEvent) {
+  fun onInit(event: FMLPostInitializationEvent) {
```
Comment (TheElan) [inline src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/ThaumcraftResearchTweaks.kt]: Moving it later on, just in case, it doesn't need to be initialized early anyways.

File: src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/proxies/ClientSingletonInitializer.kt [hunk 2]
```diff
@@ -9,8 +8,6 @@ import org.apache.logging.log4j.Logger
 class ClientSingletonInitializer : SingletonInitializer {
   private val logger: Logger = LogManager.getLogger(ThaumcraftResearchTweaks.MOD_ID)
   override fun initialize() {
-    val aspectTree = AspectTree
-    logger.debug("Initialised $aspectTree")
```
Comment (TheElan) [inline src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/proxies/ClientSingletonInitializer.kt]: This was causing evaluation of aspect tree which is later use to determine aspect location (right or left). We were missing the aspect, since it was added in `FMLPostInitializationEvent` event.

Decided to skip this init anyways to avoid similar bugs in future. 

Unless somebody can propose a clever way to run inits after all mods run (or at least do it with best effort) - we will need to make do with micro freeze on first thaumcraft table opening (it's basically initializing the tree). This will be a one-off since it will stay cached till game restart.

File: src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/ThaumcraftResearchTweaks.kt [hunk 3]
```diff
@@ -35,7 +35,7 @@ object ThaumcraftResearchTweaks {
   lateinit var singletonInitializer: SingletonInitializer
 
   @Mod.EventHandler
-  fun onInit(event: FMLInitializationEvent) {
+  fun onInit(event: FMLLoadCompleteEvent) {
```
Comment (TheElan) [inline src/main/kotlin/elan/tweaks/thaumcraft/research/frontend/integration/ThaumcraftResearchTweaks.kt:38]: Tested and confirmed init order issue. Avaria creates it's aspects in `FMLPostInitializationEvent`. While this mod caches aspect tree on normal init. Moving it to latest possible init instead.

**Review by Alastors — APPROVED** [review]
